apiVersion: apps/v1
kind: Deployment
metadata:
  name: julyartifact
  labels:
    app: tomcat
  namespace: wasim
spec:
  template:
    spec:
      containers:
      - name: julyartifact
        image: artifactimage
        ports:
        - containerPort: 8080
    metadata:
      name: julyartifact
      labels:
        app: tomcat
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
      

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: wasim
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: tomcat
  type: NodePort
