apiVersion: apps/v1
kind: Deployment
metadata:
  name: julyartifact-deployment
  labels:
    app: tomcat1
  namespace: wasim
spec:
  template:
    spec:
      containers:
      - name: artifactimage
        image: 
        ports:
        - containerPort: 8080
    metadata:
      name: julyartifact-deployment
      labels:
        app: tomcat1
  replicas: 3
  selector:
    matchLabels:
      app: tomcat1
      

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat1-service
  namespace: wasim
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: tomcat1
  type: NodePort
