apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat2-deployment
  labels:
    app: tomcat2
spec:
  template:
    spec:
      containers:
      - name: tomcat2-deployment
        image: javawebapp/artifactimage
        ports:
        - containerPort: 8080
    metadata:
      name: tomcat2-deployment
      labels:
        app: tomcat2
  replicas: 1
  selector:
    matchLabels:
      app: tomcat2
      

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat2-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: tomcat2
  type: NodePort
